### ISSUE TITLE
Provide an example cabal file

### ISSUE THREAD

**Issue by christopheryoung** [haskell-servant/example-servant-minimal#2]
Did you mean to add the cabal file to the .gitignore?  Without it, a naive and inexperienced newcomer (e.g., me) runs into trouble at the second step in the README. Typing "stack test --fast" results in an error message complaining about a missing cabal file.

**Comment by soenkehahn** [comment]
`stack` supports creating cabal files with `hpack` since version `1.0.4`. Which version are you using?

**Comment by christopheryoung** [comment]
That was it. I thought I had upgraded my version of stack immediately before starting, but hadn't. Thank you very much.
